[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-multipart = "0.4"
calamine = "0.16"
serde = "1.0"
serde_json = "1.0"
csv = "1.1"
futures = "0.3"
sanitize-filename = "0.4"
uuid = { version = "1", features = ["v4"] }